language: ruby

sudo: 'required'

services:
  - 'docker'

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build . --tag aperdomob/dotnet-sonnarscanner
  - docker push aperdomob/dotnet-sonnarscanner
