language: ruby

sudo: 'required'

services:
  - 'docker'

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . --tag aperdomob/dotnet-sonnarscanner
  - docker push aperdomob/dotnet-sonnarscanner
